export const ADD_TASK= "ADD_TASK";

export const DELETE_TASK= "DELETE_TASK";

export const EDIT_TASK= "EDIT_TASK";

export const FILTER_TASK= "FILTER_TASK";
//HANDLE_FILTER_CHANGE
export const HANDLE_FILTER_CHANGE= "HANDLE_FILTER_CHANGE";
// export const HANDLE_TITLE_CHANGE= "HANDLE_TITLE_CHANGE";
// export const HANDLE_DATE_CHANGE= "HANDLE_DATE_CHANGE";
// export const HANDLE_DESCRIPTION_CHANGE= "HANDLE_DESCRIPTION_CHANGE";



